# Generated by Django 5.1 on 2024-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
